version: '3'

networks:
  openhouse:
    driver: bridge
# networks:
#   default:

services:
  dev:
    image: node:14.3.0
    networks:
        - openhouse
    # network: host
    volumes:
      - nodemodules:/usr/src/service/node_modules
      - .:/usr/src/service
    working_dir: /usr/src/service
    environment:
      - NODE_ENV=development
    command: npm run dev
    ports:
      - "3000:3000"

volumes:
  nodemodules:
    # external: true