version: "3"

networks:
  app-network:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: app
    container_name: app
    networks:
      - app-network
    command: npm start
    ports:
      - "3000:3000"
    restart: always

  nginx:
    image: nginx
    container_name: nginx
    networks:
      - app-network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
